name:  Build and Deploy to AWS EB

on:
  push:
    branches: [main]

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2

     - name:  Set up Python 3.8
       uses: actions/setup-python@v1
       with:
         python-version: "3.8"
      
     - name:  Get pip cache dir
       id: pip-cache
       run: |
          echo "::set-output name=dir::$(pip cache dir)"
        
     - name:  Cache pip
       uses: actions/cache@v1
       with:
         path: ${{ steps.pip-cache.outputs.dir }}
         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
         restore-keys: |
           ${{ runner.os }}-pip-
          
      # Install dependencies
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt

      # Run our unit tests
     - name: Run unit tests
       run: |
          python test_app.py